### ISSUE TITLE
Can't build and run

### ISSUE THREAD

**Issue by ewoody** [instamobile/recipes-app-react-native#1]
I can't build and run this app on Mac. 

What I did
1. npm install
2. react-native run-ios --simulator="iPhone 8"

The error on iOS simulator - 

Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(index.js: Cannot find module '/Users/myname/Projects/FoodApp/node_modules/@react-native-community/cli/node_modules/metro-react-native-babel-transformer/src/index.js'
Require stack:
- /Users/myname/Projects/FoodApp/node_modules/metro/src/JSTransformer/worker.js
- /Users/myname/Projects/FoodApp/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/myname/Projects/FoodApp/node_modules/metro/node_modules/jest-worker/build/child.js (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.213
    RCTCxxBridge.mm:414
invocation function for block in attemptAsynchronousLoadOfBundleAtURL(NSURL*, void (RCTLoadingProgress*) block_pointer, void (NSError*, RCTSource*) block_pointer)
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
_CFNetworkHTTPConnectionCacheSetLimit
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
__NSOPERATION_IS_INVOKING_MAIN__
-[NSOperation start]
__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
__NSOQSchedule_f
_dispatch_block_async_invoke2
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

**Comment by mrcflorian** [comment]
All you need to do is run "npm install && expo start". Closing this since it was on a very old version - let me know if you still encounter any issues with the new updates
